server:
  port: ${port:8080}

spring:
  application:
    name: first-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices
      username: micro
      password: micro


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: DEBUG
  file: app.log



name: first-service
my:
  servers:
    - dev.bar.com
    - foo.bar.com

management:
  endpoints:
    web:
      exposure:
        include: "*"

